### ISSUE TITLE
Question about auto-check

### ISSUE THREAD

**Issue by Betswish** [GenBench/genbench_cbt_2023#13]
Hi,

I submitted a PR 'Cross Lingual Consistency' last week. 
But when I checked it today, it still showed 'Some checks haven't been completed yet.'
![image](https://github.com/GenBench/genbench_cbt/assets/131008659/45e95e50-8607-4ae8-a782-970a9c0ab7d8)

I checked the 'Actions' and found all checks are already done.
![image](https://github.com/GenBench/genbench_cbt/assets/131008659/3c93acb4-ee97-43c1-b095-5befedf09c4c)

I'm not sure if it's ok to just leave it there. Do you have any suggestions?

Thanks in advance!

**Comment by vernadankers** [comment]
Hi there, all that was needed to start those checks was adding the "task-submission" label. I'm not quite sure why the checks didn't start, but I removed and re-added the label just now, and it looks like it worked. The checks are currently being performed.

**Comment by vernadankers** [comment]
Please take a look at the outcome and perform updates where needed, you can trigger them again by including the "task-submission" label.

**Comment by Betswish** [comment]
Hi vernadankers, thanks for your reply!
I modified the file and submitted it again. The "task-submission" label exists, but the checks still don't work.

Besides, the label seems unchangeable from our side. So I'd appreciate it if you can help to remove and re-add it! : )

**Comment by vernadankers** [comment]
I think you should be able to change the labels; see my pointer in this little screenshot.
I did just remove and re-add the label for you, and it looks like all checks succeed now!
![image](https://github.com/GenBench/genbench_cbt/assets/14915179/15fbebaf-a37a-41ab-948f-523f08d3080b)

**Comment by Betswish** [comment]
Actually, not ...
![image](https://github.com/GenBench/genbench_cbt/assets/131008659/4f006bb7-5985-4986-8fc7-f28017322056)

As far as I remember, all original PRs don't have any labels when first submitted.
The labels seemed to be assigned manually by kazemnejad.

Well anyway, it works out now. : ) 
Thanks again for your help! (And hope my case could help with other submissions.)

**Comment by vernadankers** [comment]
Ah thanks for pointing that out! It's probably because I'm an organiser then. Anyway, happy to see it worked out.
