### ISSUE TITLE
Issue with extracting the task name from the submission title

### ISSUE THREAD

**Issue by CLCL-Geneva** [GenBench/genbench_cbt_2023#17]
Hello

There is an issue with the command that should extract the task name from the submission title, it is run before test_task: it should allow for underscores in the name of the repositories.

The current command is this (for my submission):

task_id=$(echo '[Task Submission] BLM_tasks (`blm_tasks`)' | sed -n -e 's/^\[Task Submission\][[:alnum:][:space:]()]\+[[:space:]]*(`\([^`]*\)`)[[:space:]]*.*/\1/p')

When it also allow underscores in the repository name it works ok:

task_id=$(echo '[Task Submission] BLM_tasks (`blm_tasks`)' | sed -n -e 's/^\[Task Submission\][[:alnum:]_[:space:]()]\+[[:space:]]*(`\([^`]*\)`)[[:space:]]*.*/\1/p')

Vivi

**Comment by kazemnejad** [comment]
Thanks Vivi. Fixed the issue!

**Comment by CLCL-Geneva** [comment]
Do I need to make another pull request to have the tests rerun, or is there a way to run the last test only?

**Comment by kazemnejad** [comment]
No need for that. I already rerun the tests for your PR. and they passed successfully :)

**Comment by CLCL-Geneva** [comment]
Thank you!
